# Generated by Django 6.0.6 on 2026-07-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('EMPLOYEES', 'Employees'), ('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('PAYROLL', 'Payroll'), ('BENEFITS', 'Benefits'), ('PERFORMANCE', 'Performance'), ('DISCIPLINARY', 'Disciplinary'), ('REPORTS', 'Reports'), ('AUDIT', 'Audit'), ('SETTINGS', 'Settings')], max_length=50)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
