# Generated by Django 6.0.6 on 2026-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='data_scope',
            field=models.CharField(choices=[('OWN', 'Own Records'), ('DEPARTMENT', 'Department'), ('BRANCH', 'Branch'), ('ORGANIZATION', 'Entire Organization')], default='OWN', max_length=20),
        ),
    ]
