# Generated by Django 6.0.6 on 2026-07-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('PAYROLL', 'Payroll'), ('PERFORMANCE', 'Performance'), ('TRAINING', 'Training'), ('CONTRACT', 'Contract'), ('BENEFIT', 'Benefit'), ('EXECUTIVE', 'Executive Dashboard')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('default_export_format', models.CharField(choices=[('JSON', 'JSON'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('JSON', 'JSON'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('PAYROLL', 'Payroll'), ('PERFORMANCE', 'Performance'), ('TRAINING', 'Training'), ('CONTRACT', 'Contract'), ('BENEFIT', 'Benefit'), ('EXECUTIVE', 'Executive Dashboard')], max_length=30)),
                ('filters', models.JSONField(default=dict)),
                ('export_format', models.CharField(choices=[('JSON', 'JSON'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
