# Generated by Django 6.0.6 on 2026-07-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_approvalworkflow_userdelegation_approvalstep'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('EMPLOYEE', 'Employee'), ('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('PAYSLIP', 'Payslip'), ('CONTRACT', 'Contract'), ('PERFORMANCE', 'Performance'), ('TRAINING', 'Training'), ('BENEFIT', 'Benefit'), ('SYSTEM', 'System')], default='ANNOUNCEMENT', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('IN_APP_EMAIL', 'In-App and Email')], default='IN_APP', max_length=20)),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('ROLE', 'Specific Role'), ('DEPARTMENT', 'Specific Department'), ('BRANCH', 'Specific Branch'), ('SELECTED_USERS', 'Selected Users')], default='ALL', max_length=30)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('selected_users', models.ManyToManyField(blank=True, related_name='selected_notification_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_broadcasts', to='departments.department')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_broadcasts', to='accounts.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('leave_notifications', models.BooleanField(default=True)),
                ('attendance_notifications', models.BooleanField(default=True)),
                ('payroll_notifications', models.BooleanField(default=True)),
                ('contract_notifications', models.BooleanField(default=True)),
                ('performance_notifications', models.BooleanField(default=True)),
                ('training_notifications', models.BooleanField(default=True)),
                ('benefit_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('EMPLOYEE', 'Employee'), ('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('PAYSLIP', 'Payslip'), ('CONTRACT', 'Contract'), ('PERFORMANCE', 'Performance'), ('TRAINING', 'Training'), ('BENEFIT', 'Benefit'), ('SYSTEM', 'System')], default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('IN_APP_EMAIL', 'In-App and Email')], default='IN_APP', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', 'created_at'], name='notif_recipient_date_idx'), models.Index(fields=['notification_type'], name='notif_type_idx'), models.Index(fields=['priority'], name='notif_priority_idx')],
            },
        ),
    ]
