# Generated by Django 6.0.6 on 2026-07-16 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_employeeasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed Term'), ('PROBATION', 'Probation'), ('INTERNSHIP', 'Internship'), ('CONSULTANCY', 'Consultancy'), ('CASUAL', 'Casual')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('terms', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/documents/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('DISMISSAL', 'Dismissal'), ('REDUNDANCY', 'Redundancy'), ('RETIREMENT', 'Retirement'), ('END_OF_CONTRACT', 'End of Contract'), ('MUTUAL_AGREEMENT', 'Mutual Agreement'), ('OTHER', 'Other')], max_length=30)),
                ('termination_date', models.DateField()),
                ('reason', models.TextField()),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('final_settlement_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_terminated', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='contracts.employmentcontract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_date', models.DateField(blank=True, null=True)),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('previous_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_renewals', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.employmentcontract')),
            ],
            options={
                'ordering': ['-renewed_at'],
            },
        ),
    ]
