# Generated by Django 6.0.6 on 2026-07-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_salaryhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('benefit_type', models.CharField(choices=[('MEDICAL', 'Medical Insurance'), ('PENSION', 'Pension'), ('LIFE_INSURANCE', 'Life Insurance'), ('TRANSPORT', 'Transport'), ('MEAL', 'Meal'), ('AIRTIME', 'Airtime'), ('GYM', 'Gym'), ('SACCO', 'SACCO'), ('WELFARE', 'Welfare'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('contribution_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_enrollments_approved', to=settings.AUTH_USER_MODEL)),
                ('benefit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_enrollments', to='benefits.benefitplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='employees.employee')),
                ('enrollment_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='benefits.enrollmentwindow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitContributionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_month', models.PositiveIntegerField()),
                ('payroll_year', models.PositiveIntegerField()),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_history', to='benefits.employeebenefit')),
            ],
            options={
                'ordering': ['-payroll_year', '-payroll_month'],
                'constraints': [models.UniqueConstraint(fields=('employee_benefit', 'payroll_month', 'payroll_year'), name='unique_benefit_contribution_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeebenefit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE', 'SUSPENDED'])), fields=('employee', 'benefit_plan'), name='unique_open_employee_benefit'),
        ),
    ]
