# Generated by Django 6.0.6 on 2026-07-10 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('departments', '0001_initial'),
        ('employees', '0007_employeeasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecorrectionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='attendancelocationlog',
            options={'ordering': ['-captured_at']},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', '-check_in_time']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='worklocation',
            options={'ordering': ['branch__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancelocationlog',
            name='distance_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocationlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='departments.branch'),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worklocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='worklocation',
            unique_together={('branch', 'name')},
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_per_day'),
        ),
    ]
