# Generated by Django 6.0.6 on 2026-07-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancecorrectionrequest_options_and_more'),
        ('employees', '0007_employeeasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_assignment', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='attendance.shift')),
                ('work_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='attendance.worklocation')),
            ],
            options={
                'ordering': ['employee__employee_number'],
            },
        ),
    ]
