# Generated by Django 6.0.6 on 2026-07-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employeeattendanceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('EARLY_LEAVE', 'Early Leave'), ('OVERTIME', 'Overtime'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('INCOMPLETE', 'Incomplete')], default='PRESENT', max_length=30),
        ),
    ]
