# Generated by Django 6.0.6 on 2026-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecord_status'),
        ('employees', '0008_salaryhistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='attendance_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'status'], name='attendance_emp_status_idx'),
        ),
    ]
