# Generated by Django 6.0.6 on 2026-07-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_salaryhistory'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('teamwork', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('leadership', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('technical_skill', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('innovation', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('initiative', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('productivity', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('problem_solving', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('customer_service', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_rating', models.CharField(blank=True, max_length=50)),
                ('recommend_promotion', models.BooleanField(default=False)),
                ('recommend_salary_increment', models.BooleanField(default=False)),
                ('recommend_bonus', models.BooleanField(default=False)),
                ('recommend_training', models.BooleanField(default=False)),
                ('recommend_pip', models.BooleanField(default=False)),
                ('manager_comments', models.TextField(blank=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('HR_APPROVED', 'HR Approved'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=30)),
                ('review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_app_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_app_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='performance.performancereview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='performance.performancereview')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='performance/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='performance.performancereview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('employee', 'cycle'), name='unique_employee_review_per_cycle'),
        ),
    ]
