# Generated by Django 6.0.6 on 2026-07-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeeasset'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('TAX', 'Tax')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_components', to='employees.employee')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_components', to='payroll.paycomponent')),
            ],
            options={
                'unique_together': {('employee', 'component')},
            },
        ),
    ]
