# Generated by Django 6.0.6 on 2026-07-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_paycomponent_employeepaycomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('is_base_currency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('statutory_type', models.CharField(choices=[('NSSF', 'NSSF'), ('SHIF', 'SHIF'), ('HOUSING_LEVY', 'Housing Levy'), ('PENSION', 'Pension'), ('OTHER', 'Other')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_percentage', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PAYE', max_length=100)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('working_days_per_month', models.PositiveIntegerField(default=22)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('weekend_overtime_multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('payroll_cutoff_day', models.PositiveIntegerField(default=25)),
                ('payslip_generation_day', models.PositiveIntegerField(default=28)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_policies', to='payroll.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='payroll.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='payroll.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
