# Generated by Django 6.0.6 on 2026-07-22 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_options_employee_emp_status_idx_and_more'),
        ('payroll', '0004_rebuild_payroll_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['year', 'month', 'status'], name='payrun_year_month_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['created_at'], name='payrun_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'payroll_run'], name='payslip_emp_run_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll_run'], name='payslip_run_idx'),
        ),
    ]
