# Generated by Django 6.0.6 on 2026-07-02 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('disability_status', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('national_id_number', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('tax_pin', models.CharField(blank=True, max_length=100)),
                ('social_security_number', models.CharField(blank=True, max_length=100)),
                ('health_insurance_number', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('CASUAL', 'Casual'), ('CONSULTANT', 'Consultant')], default='PERMANENT', max_length=30)),
                ('employment_status', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('OFFBOARDED', 'Offboarded')], default='ONBOARDING', max_length=30)),
                ('work_location', models.CharField(blank=True, max_length=150)),
                ('job_grade', models.CharField(blank=True, max_length=50)),
                ('job_level', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.branch')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.designation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('CV', 'CV'), ('ACADEMIC_CERTIFICATE', 'Academic Certificate'), ('PROFESSIONAL_CERTIFICATE', 'Professional Certificate'), ('TAX_DOCUMENT', 'Tax Document'), ('BANK_DOCUMENT', 'Bank Document'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='employees/documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='employees/education/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employees.employee')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
