# Generated by Django 6.0.6 on 2026-07-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeedependant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employees/certifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employees.employee')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
