# Generated by Django 6.0.6 on 2026-07-22 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_metadata_auditlog_model_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_module_action_idx',
            old_name='audit_audit_module_365bd8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_user_date_idx',
            old_name='audit_audit_user_id_a3c2bc_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_object_idx',
            old_name='audit_audit_model_n_20c0d3_idx',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_action_date_idx'),
        ),
    ]
